import * as dotenv from "dotenv";

dotenv.config();

export interface AppConfig {
  GOOGLE_API_KEY: string;
  LINKEDIN_ACCESS_TOKEN: string;
  LINKEDIN_PERSON_URN: string;
  TOPIC?: string;
  CONTEXT: string;
  SUPABASE_URL: string;
  SUPABASE_SERVICE_ROLE_KEY: string;
  ENCRYPTION_KEY: string;
  LINKEDIN_CLIENT_ID: string;
  LINKEDIN_CLIENT_SECRET: string;
  LINKEDIN_REDIRECT_URI: string;
}

export function loadConfig(): AppConfig {
  const {
    GOOGLE_API_KEY, LINKEDIN_ACCESS_TOKEN, LINKEDIN_PERSON_URN, TOPIC, CONTEXT,
    SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY, ENCRYPTION_KEY,
    LINKEDIN_CLIENT_ID, LINKEDIN_CLIENT_SECRET, LINKEDIN_REDIRECT_URI
  } = process.env;

  return {
    GOOGLE_API_KEY: GOOGLE_API_KEY || "",
    LINKEDIN_ACCESS_TOKEN: LINKEDIN_ACCESS_TOKEN || "",
    LINKEDIN_PERSON_URN: LINKEDIN_PERSON_URN || "",
    TOPIC,
    CONTEXT: CONTEXT || "",
    SUPABASE_URL: SUPABASE_URL || "",
    SUPABASE_SERVICE_ROLE_KEY: SUPABASE_SERVICE_ROLE_KEY || "",
    ENCRYPTION_KEY: ENCRYPTION_KEY || "",
    LINKEDIN_CLIENT_ID: LINKEDIN_CLIENT_ID || "",
    LINKEDIN_CLIENT_SECRET: LINKEDIN_CLIENT_SECRET || "",
    LINKEDIN_REDIRECT_URI: LINKEDIN_REDIRECT_URI || "",
  };
}

export const config = loadConfig();
